### ISSUE TITLE
Error feature extraction: unpack requires a string argument of length 8

### ISSUE THREAD

**Issue by 7homasSutter** [alexMyG/AndroPyTool#20]
Hi there,
when I run AndroPyTool in docker with `docker run --volume=./test/:/apks alexmyg/andropytool -s /apks/ -fw -f -mg 127.0.0.1:27017` the container crashes at step 7. 

The stack trace: 
```
>>>> AndroPyTool -- STEP 7: Execute features extraction

[*] Number of APKs: 1
ANALYSING APKS...
  0%|          | 0/1 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/root/AndroPyTool/androPyTool.py", line 320, in <module>
    main()
    -> <function main at 0x7ff330158398>
  File "/root/AndroPyTool/androPyTool.py", line 164, in main
    virus_total_api_key=step_analyse_virus_total
                        -> None
  File "/root/AndroPyTool/androPyTool.py", line 316, in execute_andro_py_tool_steps
    export_csv=exportCSV)
  File "/root/AndroPyTool/APT_6_feat_extraction.py", line 223, in features_extractor
    static_analysis_dict['Opcodes'] = opcodes_analysis(androguard_apk_object)
    |                                 |                -> <androguard.core.bytecodes.apk.APK object at 0x7ff33008cc50>
    |                                 -> <function opcodes_analysis at 0x7ff33384ede8>
    -> OrderedDict([('Package name', u'com.android.certinstaller'), ('Permissions', ['android.permission.CHANGE_WIFI_STATE', 'android.p...
  File "/root/AndroPyTool/features_managment.py", line 14, in opcodes_analysis
    dalvik = dvm.DalvikVMFormat(androguard_apk.get_dex())
             |                  -> <androguard.core.bytecodes.apk.APK object at 0x7ff33008cc50>
             -> <module 'androguard.core.bytecodes.dvm' from '/usr/local/lib/python2.7/dist-packages/androguard/core/bytecodes/dvm.pyc'>
  File "/usr/local/lib/python2.7/dist-packages/androguard/core/bytecodes/dvm.py", line 7305, in __init__
    self._load(buff)
    |          -> ''
    -> <androguard.core.bytecodes.dvm.DalvikVMFormat object at 0x7ff33008cd90>
  File "/usr/local/lib/python2.7/dist-packages/androguard/core/bytecodes/dvm.py", line 7311, in _load
    self.__header = HeaderItem(0, self, ClassManager(None, self.config))
    |               |             |     |                  -> <androguard.core.bytecodes.dvm.DalvikVMFormat object at 0x7ff33008cd90>
    |               |             |     -> <class 'androguard.core.bytecodes.dvm.ClassManager'>
    |               |             -> <androguard.core.bytecodes.dvm.DalvikVMFormat object at 0x7ff33008cd90>
    |               -> <class 'androguard.core.bytecodes.dvm.HeaderItem'>
    -> <androguard.core.bytecodes.dvm.DalvikVMFormat object at 0x7ff33008cd90>
  File "/usr/local/lib/python2.7/dist-packages/androguard/core/bytecodes/dvm.py", line 363, in __init__
    self.magic = unpack("=Q", buff.read(8))[0]
    |            |            -> <androguard.core.bytecodes.dvm.DalvikVMFormat object at 0x7ff33008cd90>
    |            -> <built-in function unpack>
    -> <androguard.core.bytecodes.dvm.HeaderItem object at 0x7ff3300b62d0>
error: unpack requires a string argument of length 8
```
Is there a way to skip this step?

**Comment by Zesok** [comment]
I have the same issue, did you find a workaround?

**Comment by 3BBUAE** [comment]
HelloI have the same issue as well, it seems to be androguard problem I have installed the latest version of androguard.
![image](https://user-images.githubusercontent.com/15378788/86026852-03589900-ba41-11ea-9bbc-b47d3529572e.png)
