### ISSUE TITLE
"NO JSON object could be decoded" in droidbox

### ISSUE THREAD

**Issue by Lakshmanarao1216** [alexMyG/AndroPyTool#23]
File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

I am using method_A: docker

**Comment by 0xSmash0th** [comment]
I am also getting this issue. Run with: sudo docker run --volume=/home/owner/one_sample:/apks alexmyg/andropytool -s /apks/ -all --color
also run without sudo
Also using docker 


>>>> AndroPyTool -- STEP 7: Execute features extraction

[*] Number of APKs: 1
ANALYSING APKS...
  0%|          | 0/1 [00:00<?, ?it/s]Creating filesystem with parameters:
    Size: 69206016
    Block size: 4096
    Blocks per group: 32768
    Inodes per group: 4224
    Inode size: 256
    Journal blocks: 1024
    Label: 
    Blocks: 16896
    Block groups: 1
    Reserved block group size: 7
Created filesystem with 11/4224 inodes and 1302/16896 blocks

Traceback (most recent call last):
  File "/root/AndroPyTool/androPyTool.py", line 320, in <module>
    main()
    -> <function main at 0x7f5180cc71d0>
  File "/root/AndroPyTool/androPyTool.py", line 164, in main
    virus_total_api_key=step_analyse_virus_total
                        -> None
  File "/root/AndroPyTool/androPyTool.py", line 316, in execute_andro_py_tool_steps
    export_csv=exportCSV)
  File "/root/AndroPyTool/APT_6_feat_extraction.py", line 346, in features_extractor
    dynamic_analysis_dict[dynamic_tool_name] = json.load(open(dynamic_file_name))
    |                     |                    |              -> '/apks/Dynamic/Droidbox/EasterEgg.json'
    |                     |                    -> <module 'json' from '/usr/lib/python2.7/json/__init__.pyc'>
    |                     -> 'Droidbox'
    -> OrderedDict()
  File "/usr/lib/python2.7/json/__init__.py", line 291, in load
    **kw)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
           |                       -> ''
           -> <json.decoder.JSONDecoder object at 0x7f51896ebe10>
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               |               |      |  -> ''
               |               |      -> <built-in method match of _sre.SRE_Pattern object at 0x7f51896e50d0>
               |               -> ''
               -> <json.decoder.JSONDecoder object at 0x7f51896ebe10>
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

**Comment by dpt1305** [comment]
I also getting this issue, how we can fix this error.
I just run this command "docker run --volume=</PATH/TO/FOLDER/WITH/APKS/>:/apks alexmyg/andropytool -s /apks/ -dr". 
I realized this error just occur in some file, not at all.
"  0%|          | 0/5 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/root/AndroPyTool/androPyTool.py", line 320, in <module>
    main()
    -> <function main at 0x7f3b2815f1d0>
  File "/root/AndroPyTool/androPyTool.py", line 164, in main
    virus_total_api_key=step_analyse_virus_total
                        -> None
  File "/root/AndroPyTool/androPyTool.py", line 316, in execute_andro_py_tool_steps
    export_csv=exportCSV)
  File "/root/AndroPyTool/APT_6_feat_extraction.py", line 346, in features_extractor
    dynamic_analysis_dict[dynamic_tool_name] = json.load(open(dynamic_file_name))
    |                     |                    |              -> '/apks/Dynamic/Droidbox/000a75c02f4a442a4876448fc537826e.json'
    |                     |                    -> <module 'json' from '/usr/lib/python2.7/json/__init__.pyc'>
    |                     -> 'Droidbox'
    -> OrderedDict()
  File "/usr/lib/python2.7/json/__init__.py", line 291, in load
    **kw)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
           |                       -> ''
           -> <json.decoder.JSONDecoder object at 0x7f3b3c193e10>
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               |               |      |  -> ''
               |               |      -> <built-in method match of _sre.SRE_Pattern object at 0x7f3b3c18d0d0>
               |               -> ''
               -> <json.decoder.JSONDecoder object at 0x7f3b3c193e10>
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded"

**Comment by vanderson-rocha** [comment]
I also getting this issue, how we can fix this error
